EW-5763 Adding command to generate random secret token
akamai/cli-edgeworkers pull request #12
Opened 2020-09-30 20:53 UTC by swathimr

https://track.akamai.com/jira/browse/EW-5763

This reuses the cryptoJS library to generate random secret token

2020-09-30 20:54 UTC, swathimr commented
@sscian @ananner

2020-10-01 21:18 UTC, dctheobald requested changes
Minor README changes needed; rest of code looks great, thanks!

2020-10-01 21:18 UTC, dctheobald commented on README.md
> +Usage: `node akamai-edgeworkers generate-secret [options]`
Usage example should not reference node directly.

2020-10-01 21:18 UTC, dctheobald commented on src/cli-main.ts
> +  .description("Generated a random secret key that can be used in the variable PMUSER_EW_DEBUG_KEY in their property and as an input to create auth token using cli command")
Generates not 'Generated'?

2020-10-02 01:09 UTC, dctheobald approved these changes
Looks good to me.

2020-10-16 21:36 UTC, merged