Resource tier support for CLI
akamai/cli-edgeworkers pull request #30
Opened 2021-03-30 17:33 UTC by swathimr

Updates to existing API:
 - Create new edgeworker
 - Edit an EdgeWorker ID
 - Fetch EdgeWorker IDs

New Endpoints
- Clone an EdgeWorker ID
- List Contract IDs for Resource Tiers
- List Resource Tiers for a specific Contract ID
- Fetch the Resource Tier for a specific EdgeWorker ID

2021-03-30 17:54 UTC, mryakan commented
We need to also update the readme as part of this PR.

2021-04-05 17:32 UTC, surbhi65 approved these changes

2021-04-05 17:32 UTC, surbhi65 commented on README.md
> +| show-restier \| show-restier `<edgeworker-identifier>` | Customers can get Resource Tier details for a specific EdgeWorker Id. |
very minor but **show-res-tier** might be easy to understand. same for **list-res-tier**

2021-04-05 17:32 UTC, surbhi65 commented on README.md
> +
what are [options] for?

2021-04-05 17:32 UTC, surbhi65 commented on docs/edgekv_cli.md
> +| -o, --overwrite | Optional | This option is used in conjunction with the --save_path option to overwrite the value of an existing token with the same name in the edgekv_tokens.js file. |
**file.If** missing space before If

2021-04-05 17:32 UTC, surbhi65 commented on docs/edgekv_cli.md
> +| -o, --overwrite | Optional | This option is used in conjunction with the --save_path option to overwrite the value of an existing token with the same name in the edgekv_tokens.js file. |
whats the difference between -- and - parameters like --save_path and -o?

2021-04-05 18:24 UTC, mryakan requested changes

2021-04-05 18:24 UTC, mryakan commented on docs/edgekv_cli.md
> +`akamai edgekv create token <tokenName> --save_path=<path> --overwrite`
should be "download" not "create"

2021-04-05 21:14 UTC, merged